<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class PayrollReport extends CI_Controller
{
    public function __construct()
    {
        parent::__construct();
        $this->load->model('payroll_report_model', 'reports');
        $this->load->library("Aauth");
        if (!$this->aauth->is_loggedin()) {
            redirect('/user/', 'refresh');
        }
        
        $this->li_a = 'payroll'; // Highlight Payroll menu
    }

    public function index()
    {
        $head['usernm'] = $this->aauth->get_user()->username;
        $head['title'] = 'Payroll Reports';
        
        $this->load->view('fixed/header', $head);
        $this->load->view('payroll/report/index');
        $this->load->view('fixed/footer');
    }

    public function payslips() {
        $run_id = $this->input->get('id'); 
        $head['usernm'] = $this->aauth->get_user()->username;
        $head['title'] = 'Payroll Runs';

        if(!$run_id) {
             $data['runs'] = $this->reports->get_payroll_runs();
             $this->load->view('fixed/header', $head);
             $this->load->view('payroll/report/run_list', $data);
             $this->load->view('fixed/footer');
        } else {
             $data['run'] = $this->reports->get_run_details($run_id);
             $data['items'] = $this->reports->get_payroll_items($run_id);
             $this->load->view('fixed/header', $head);
             $this->load->view('payroll/report/payslips', $data);
             $this->load->view('fixed/footer');
        }
    }
    
    public function my_payslips() {
        $head['usernm'] = $this->aauth->get_user()->username;
        $head['title'] = 'My Payslips';
        
        $employee_id = $this->aauth->get_user()->id;
        
        // Fetch runs where this employee has a payslip item
        // Reuse model or add new method? Let's add a quick query here or ideally model.
        // For speed, let's use the model's new method 'get_employee_payslip_list' if I create it, or direct DB.
        // Let's create `get_employee_all_payslips` in `Payroll_report_model`.
        $data['payslips'] = $this->reports->get_employee_all_payslips($employee_id);
        
        $this->load->view('fixed/header', $head);
        $this->load->view('payroll/report/my_payslips', $data);
        $this->load->view('fixed/footer');
    }
    
    public function view_payslip() {
        $id = $this->input->get('id');
        $download = $this->input->get('d');
        
        $data['payslip'] = $this->reports->get_employee_payslip($id);
        
        if(!$data['payslip']) {
            echo 'Payslip not found or invalid ID.';
            return;
        }
        
        // Security Check
        $current_user_id = $this->aauth->get_user()->id;
        $payslip_employee_id = $data['payslip']['employee_id'];
        
        // Allow if Own Payslip OR Admin/Manager (Role > 3? Check implementation rules, usually roleid 5=Owner, 4=BizManager)
        // Let's assume permission(14) is HR/Payroll Admin.
        if($payslip_employee_id != $current_user_id) {
            if(!$this->aauth->premission(14) && $this->aauth->get_user()->roleid < 4) {
                 exit('<h3>Access Denied: You are not authorized to view this payslip.</h3>');
            }
        }

        $data['details'] = json_decode($data['payslip']['deduction_details'], true);
        if(!$data['details']) $data['details'] = array();
        
        // Fetch Extended Stats (OT & Jobs)
        $data['stats'] = $this->reports->get_payslip_statistics(
            $data['payslip']['employee_id'], 
            $data['payslip']['start_date'], 
            $data['payslip']['end_date']
        );
        
        // Load View as HTML
        $html = $this->load->view('payroll/report/payslip_view', $data, true);
        
        // If HTML requested or PDF not available, show HTML
        if($download == 'html' || !$download) {
            echo $html;
            return;
        }
        
        // Load PDF Library for download
        try {
            $this->load->library('pdf');
            $pdf = $this->pdf->load();
            $pdf->SetHTMLFooter('<div style="text-align: right;font-family: serif; font-size: 8pt; color: #5C5C5C; font-style: italic;margin-top:-6pt;">Generated by GeoPOS Payroll</div>');
            $pdf->WriteHTML($html);
            
            $filename = 'Payslip_' . $data['payslip']['name'] . '_' . $data['payslip']['run_id'] . '.pdf';
            $pdf->Output($filename, $download == '1' ? 'D' : 'I');
        } catch (Exception $e) {
            // If PDF fails, show HTML
            echo $html;
        }
    }
    public function export_run() {
         $run_id = $this->input->get('id');
         $items = $this->reports->get_payroll_items($run_id);
         
         header('Content-Type: text/csv');
         header('Content-Disposition: attachment; filename="payroll_run_' . $run_id . '.csv"');
         
         $fp = fopen('php://output', 'w');
         fputcsv($fp, array('Employee ID', 'Name', 'Bank Name', 'Bank Account', 'Gross Pay', 'Tax', 'Deductions', 'Net Pay'));
         
         foreach ($items as $row) {
             // Accessing DB directly here for speed as model update is separate
             $emp = $this->db->select('bank_name, bank_ac')->where('id', $row['employee_id'])->get('geopos_employees')->row_array();
             
             fputcsv($fp, array(
                 $row['employee_id'], 
                 $row['name'], 
                 isset($emp['bank_name']) ? $emp['bank_name'] : '',
                 isset($emp['bank_ac']) ? $emp['bank_ac'] : '',
                 $row['gross_pay'], 
                 $row['tax'], 
                 $row['total_deductions'], 
                 $row['net_pay']
             ));
         }
         fclose($fp);
    }

    public function tax_report() {
        $start = $this->input->post('start');
        $end = $this->input->post('end');
        
        $head['usernm'] = $this->aauth->get_user()->username;
        $head['title'] = 'Tax Reports';
        
        if($start && $end) {
            $data['runs'] = $this->reports->get_payroll_runs($start, $end);
            $data['start'] = $start; $data['end'] = $end;
             $this->load->view('fixed/header', $head);
             $this->load->view('payroll/report/tax_report', $data);
             $this->load->view('fixed/footer');
        } else {
             $this->load->view('fixed/header', $head);
             $this->load->view('payroll/report/tax_select');
             $this->load->view('fixed/footer');
        }
    }

    public function job_costing() {
        $start = $this->input->post('start');
        $end = $this->input->post('end');
        
        $head['usernm'] = $this->aauth->get_user()->username;
        $head['title'] = 'Labor Costing Report';
        
        if($start && $end) {
             $data['costs'] = $this->reports->get_job_costing_summary($start, $end);
             $data['start'] = $start; $data['end'] = $end;
             $this->load->view('fixed/header', $head);
             $this->load->view('payroll/report/job_costing', $data);
             $this->load->view('fixed/footer');
        } else {
             $this->load->view('fixed/header', $head);
             $this->load->view('payroll/report/job_costing_select');
             $this->load->view('fixed/footer');
        }
    }

    public function send_payslip() {
        $id = $this->input->post('id');
        $payslip = $this->reports->get_employee_payslip($id);
        
        if(!$payslip) {
            echo json_encode(array('status' => 'Error', 'message' => 'Payslip not found'));
            return;
        }
        
        if(empty($payslip['email'])) {
             echo json_encode(array('status' => 'Error', 'message' => 'Employee email not found. Please update employee profile.'));
             return;
        }

        $data['payslip'] = $payslip;
        $data['details'] = json_decode($payslip['deduction_details'], true);

        // 1. Generate PDF
        $this->load->library('pdf');
        $pdf = $this->pdf->load();
        $html = $this->load->view('payroll/report/payslip_view', $data, true);
        $pdf->SetHTMLFooter('<div style="text-align: right;font-family: serif; font-size: 8pt; color: #5C5C5C; font-style: italic;margin-top:-6pt;">Generated by GeoPOS Payroll</div>');
        $pdf->WriteHTML($html);
        
        $filename = 'Payslip_' . $payslip['name'] . '_' . $payslip['run_id'] . '.pdf';
        $file_path = FCPATH . 'userfiles/temp/' . $filename;
        
        // Ensure temp dir exists
        if (!is_dir(FCPATH . 'userfiles/temp/')) {
            mkdir(FCPATH . 'userfiles/temp/', 0777, true);
        }
        
        $pdf->Output($file_path, 'F');
        
        // 2. Send Email
        $this->load->model('communication_model');
        $subject = "Payslip for period: " . date('Y-m-d', strtotime($payslip['start_date']));
        $message = "Dear " . $payslip['name'] . ",<br><br>Please find attached your payslip for the period " . $payslip['start_date'] . " to " . $payslip['end_date'] . ".<br><br>Regards,<br>" . $this->config->item('ctitle');
        
        // send_email($mailto, $mailtotitle, $subject, $message, $attachmenttrue = false, $attachment = '')
        $this->communication_model->send_email($payslip['email'], $payslip['name'], $subject, $message, true, $file_path);
        
        // 3. Cleanup
        if(file_exists($file_path)) {
            unlink($file_path);
        }
        
        echo json_encode(array('status' => 'Success', 'message' => 'Payslip emailed to ' . $payslip['email']));
    }

    public function dashboard() {
        $head['usernm'] = $this->aauth->get_user()->username;
        $head['title'] = 'Payroll Dashboard';
        
        $data['stats'] = $this->reports->get_dashboard_stats();
        
        $this->load->view('fixed/header', $head);
        $this->load->view('payroll/report/dashboard', $data);
        $this->load->view('fixed/footer');
    }
}
