<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Cutting Instruction Sheet #<?php echo $plan['id']; ?></title>
    
    <style>
    .invoice-box {
        max-width: 800px;
        margin: auto;
        padding: 30px;
        border: 1px solid #eee;
        box-shadow: 0 0 10px rgba(0, 0, 0, .15);
        font-size: 16px;
        line-height: 24px;
        font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
        color: #555;
    }
    
    .invoice-box table {
        width: 100%;
        line-height: inherit;
        text-align: left;
    }
    
    .invoice-box table td {
        padding: 5px;
        vertical-align: top;
    }
    
    .invoice-box table tr td:nth-child(2) {
        text-align: right;
    }
    
    .invoice-box table tr.top table td {
        padding-bottom: 20px;
    }
    
    .invoice-box table tr.top table td.title {
        font-size: 45px;
        line-height: 45px;
        color: #333;
    }
    
    .invoice-box table tr.information table td {
        padding-bottom: 40px;
    }
    
    .invoice-box table tr.heading td {
        background: #eee;
        border-bottom: 1px solid #ddd;
        font-weight: bold;
    }
    
    .invoice-box table tr.details td {
        padding-bottom: 20px;
    }
    
    .invoice-box table tr.item td{
        border-bottom: 1px solid #eee;
    }
    
    .invoice-box table tr.item.last td {
        border-bottom: none;
    }
    
    .invoice-box table tr.total td:nth-child(2) {
        border-top: 2px solid #eee;
        font-weight: bold;
    }
    
    .visual-cut {
        border: 2px solid #000;
        background: #D2B48C; /* Wood color */
        position: relative;
        margin-top: 20px;
        height: 100px; /* Scaled height */
        width: 100%;
    }
    .plank {
        border: 1px dashed #fff;
        background: #A0522D;
        float: left;
        color: white;
        text-align: center;
        font-size: 10px;
        overflow: hidden;
    }

    @media print {
        .no-print { display: none; }
        .invoice-box { border: 0; box-shadow: none; }
    }
    </style>
</head>

<body>
    <div class="no-print" style="text-align:right; margin-bottom:10px;">
        <button onclick="window.print()">Print Sheet</button>
    </div>

    <div class="invoice-box">
        <table cellpadding="0" cellspacing="0">
            <tr class="top">
                <td colspan="2">
                    <table>
                        <tr>
                            <td class="title">
                                <h5>Cutting Instruction Sheet</h5>
                            </td>
                            
                            <td>
                                Plan #: <?php echo $plan['id']; ?><br>
                                Date: <?php echo date('Y-m-d'); ?><br>
                                Generated By: <?php echo $this->aauth->get_user()->username; ?>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            
            <tr class="information">
                <td colspan="2">
                    <table>
                        <tr>
                            <td>
                                <strong>Batch Info:</strong><br>
                                <?php echo $plan['batch_name'] ? $plan['batch_name'] : 'N/A'; ?><br>
                                Priority: <?php echo $plan['priority'] ? $plan['priority'] : 'N/A'; ?>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            
            <tr class="heading">
                <td>
                    Raw Timber Dimensions (Input)
                </td>
                
                <td>
                    Values (inches)
                </td>
            </tr>
            
            <tr class="item">
                <td>
                    Dimensions (LxWxH)
                </td>
                
                <td>
                    <?php echo $plan['raw_timber_dim']; ?>
                </td>
            </tr>
            
            <tr class="heading">
                <td>
                    Target Cuts (Output)
                </td>
                
                <td>
                    Target
                </td>
            </tr>
            
            <tr class="item">
                <td>
                   Target Plank Size
                </td>
                
                <td>
                    <?php echo $plan['plank_dim']; ?>
                </td>
            </tr>
            
            <tr class="item">
                <td>
                    Total Planks to Cut
                </td>
                
                <td>
                    <?php echo $plan['planks_count']; ?> Pcs
                </td>
            </tr>

            <tr class="total">
                <td></td>
                
                <td>
                   Expected Waste: <?php echo $plan['waste_percentage']; ?>%
                </td>
            </tr>
        </table>
        
        <br>
        <h4>Visual Guide (Concept)</h4>
        <p>This is a conceptual representation of how planks fit into the raw volume linearly.</p>
        
        <div class="visual-cut">
            <?php 
                // Simple visual: Just render divs for each plank up to a limit
                $limit = min($plan['planks_count'], 20); // Show max 20 for visual
                for($i=0; $i<$limit; $i++) {
                    echo '<div class="plank" style="width: 5%; height: 100%; display:inline-block;">P'.($i+1).'</div>';
                }
                if($plan['planks_count'] > 20) echo '... (+'.($plan['planks_count']-20).')';
            ?>
        </div>
        <div style="font-size: 10px; color: #777;">* Not to scale.</div>

        <br><br>
        <hr>
        <p style="text-align: center; font-size: 12px;">Carpenter Production Line System</p>
    </div>
</body>
</html>
